package com.tis.in.BanX.common;

/**
 * @Class All the static common message constants
 *
 */
public class CommonMessageConstants {

	private CommonMessageConstants() {
	}

	public static final String SUCCESS_USER_TYPE_CREATION = "SUCCESS_USER_TYPE_CREATION";
	public static final String SUCCESS_USER_TYPE_UPDATION = "SUCCESS_USER_TYPE_UPDATION";

	public static final String SUCCESS_USER_CREATION = "SUCCESS_USER_CREATION";
	public static final String SUCCESS_USER_UPDATION = "SUCCESS_USER_UPDATION";
	
	public static final String SUCCESS_BANK_EXAM_CREATION = "SUCCESS_BANK_EXAM_CREATION";
	public static final String SUCCESS_BANK_EXAM_UPDATION = "SUCCESS_BANK_EXAM_UPDATION";
	
	public static final String SUCCESS_STUDENT_QUALIFICATION_CREATION = "SUCCESS_STUDENT_QUALIFICATION_CREATION";
	public static final String SUCCESS_STUDENT_QUALIFICATION_UPDATION = "SUCCESS_STUDENT_QUALIFICATION_UPDATION";
	
	public static final String SUCCESS_STUDENT_USER_CREATION = "SUCCESS_STUDENT_USER_CREATION";
	public static final String SUCCESS_STUDENT_USER_UPDATION = "SUCCESS_STUDENT_USER_UPDATION";
	
	
	public static final String SUCCESS_QUESTION_CATEGORY_CREATION = "SUCCESS_QUESTION_CATEGORY_CREATION";
	public static final String SUCCESS_QUESTION_CATEGORY_UPDATION = "SUCCESS_QUESTION_CATEGORY_UPDATION";
	
	public static final String USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
	public static final String SUCCESS_RE_AUTHORIZE = "SUCCESS_RE_AUTHORIZE";
	public static final String SUCCESS_CREATE_GROUP = "SUCCESS_CREATE_GROUP";
	public static final String SUCCESS_ENABLE = "SUCCESS_ENABLE";
	public static final String SUCCESS_DISABLE = "SUCCESS_DISABLE";
	public static final String SUCCESS_GROUP_USER_MAPPING = "SUCCESS_GROUP_USER_MAPPING";
	public static final String SUCCESS_DISABLE_USER = "SUCCESS_DISABLE_USER";
	public static final String GROUPFUNCTION_SUCCESS_DISABLE = "GROUPFUNCTION_SUCCESS_DISABLE";
	public static final String GROUPFUNCTION_SUCCESS_ENABLE = "GROUPFUNCTION_SUCCESS_ENABLE";
	public static final String SUCCESS_AGENT_MAPPING_INSERT = "SUCCESS_AGENT_MAPPING_INSERT";
	public static final String SUCCESS_AGENT_MAPPING_UPDATE = "SUCCESS_AGENT_MAPPING_UPDATE";
	public static final String SUCCESS_KEYCLOAK_USER_CREATION = "KEYCLOAK_USER_CREATION";
	public static final String SUCCESS_KEYCLOAK_USER_UPDATION = "KEYCLOAK_USER_UPDATION";
	public static final String SUCCESS_KEYCLOAK_USER_RESET_PASSWORD = "KEYCLOAK_USER_RESET_PASSWORD";
	public static final String SUCCESS_CREATE_FUNCTION = "SUCCESS_CREATE_FUNCTION";
	public static final String SUCCESS_UPDATE_FUNCTION = "SUCCESS_UPDATE_FUNCTION";
	public static final String GROUP_CHANGES_AUTHORIZATION = "GROUP_CHANGES_AUTHORIZATION";
	public static final String GROUP_MAPPING_AUTHORIZATION = "GROUP_MAPPING_AUTHORIZATION";
	public static final String GROUP_APPROVAL_REQUEST = "GROUP_APPROVAL_REQUEST";
	public static final String GROUP_SUPERVISOR_APPROVED_RESPONSE = "GROUP_SUPERVISOR_APPROVED_RESPONSE";
	public static final String GROUP_SUPERVISOR_REJECTED_RESPONSE = "GROUP_SUPERVISOR_REJECTED_RESPONSE";
	public static final String USER_MAPPING_AUTHORIZATION = "USER_MAPPING_AUTHORIZATION";
	public static final String USER_APPROVAL_REQUEST = "USER_APPROVAL_REQUEST";
	public static final String USER_SUPERVISOR_APPROVED_RESPONSE = "USER_SUPERVISOR_APPROVED_RESPONSE";
	public static final String USER_SUPERVISOR_REJECTED_RESPONSE = "USER_SUPERVISOR_REJECTED_RESPONSE";
	public static final String SUCCESS_GROUP_AUTHORIZE = "SUCCESS_GROUP_AUTHORIZE";
	public static final String SUCCESS_GROUP_REJECT = "SUCCESS_GROUP_REJECT";
	public static final String SUCCESS_USER_AUTHORIZE = "SUCCESS_USER_AUTHORIZE";
	public static final String SUCCESS_USER_REJECT = "SUCCESS_USER_REJECT";
	public static final String SUCCESS_GROUP_CHANGES_REQUEST = "SUCCESS_GROUP_CHANGES_REQUEST";
	public static final String SUCCESS_GROUP_CHANGES = "SUCCESS_GROUP_CHANGES";
	public static final String SUCCESS_GROUPFUNCTION_MAPPING_REQUEST = "SUCCESS_GROUPFUNCTION_MAPPING_REQUEST";
	public static final String SUCCESS_GROUPUSER_MAPPING_REQUEST = "SUCCESS_GROUPUSER_MAPPING_REQUEST";
	public static final String SUCCESS_USERGROUP_MAPPING_REQUEST = "SUCCESS_USERGROUP_MAPPING_REQUEST";
	public static final String SUCCESS_USERAGENT_MAPPING_REQUEST = "SUCCESS_USERAGENT_MAPPING_REQUEST";
	public static final String HEADER = "header";
	public static final String FILE = "file";

	public static final String SUCCESS_USER_ROLE_MAPPING = "SUCCESS_USER_ROLE_MAPPING";
	public static final String SUCCESS_ROLE_CREATION = "SUCCESS_ROLE_CREATION";
	public static final String SUCCESS_ROLE_UPDATION = "SUCCESS_ROLE_UPDATION";
	public static final String SUCCESS_ROLE_AUTHORIZATION = "SUCCESS_ROLE_AUTHORIZATION";
	public static final String SUCCESS_ROLE_REJECTION = "SUCCESS_ROLE_REJECTION";
	public static final String SUCCESS_COMPOSITE_ROLE_MAPPING = "SUCCESS_COMPOSITE_ROLE_MAPPING";
	public static final String SUCCESS_COMPOSITE_ROLE_REMOVING = "SUCCESS_COMPOSITE_ROLE_REMOVING";
	public static final String USER_CREATION_AUTHORIZATION = "USER_CREATION_AUTHORIZATION";
	public static final String SUCCESS_ROLE_STATUS_UPDATE = "SUCCESS_ROLE_STATUS_UPDATE";
	public static final String ROLE_CHANGES_AUTHORIZATION = "ROLE_CHANGES_AUTHORIZATION";
	public static final String ROLE_MAPPING_AUTHORIZATION = "ROLE_MAPPING_AUTHORIZATION";
	public static final String ROLE_AUTHORIZATION = "ROLE_AUTHORIZATION";
	public static final String ROLE_APPROVAL_REQUEST = "ROLE_APPROVAL_REQUEST";
	public static final String ROLE_SUPERVISOR_APPROVED_RESPONSE = "ROLE_SUPERVISOR_APPROVED_RESPONSE";
	public static final String ROLE_SUPERVISOR_REJECTED_RESPONSE = "ROLE_SUPERVISOR_REJECTED_RESPONSE";
	public static final String IDAM_SUCCESS_GROUP_USER_MAPPING = "IDAM_SUCCESS_GROUP_USER_MAPPING";

	public static final String SUCCESS_USERROLES_MAPPING_REQUEST = "SUCCESS_USERROLES_MAPPING_REQUEST";
	public static final String SUCCESS_USERROLES_DISABLE = "SUCCESS_USERROLES_DISABLE";
	public static final String SUCCESS_USERROLES_ENABLE = "SUCCESS_USERROLES_ENABLE";
}
