package com.tis.in.BanX.common;

/**
 * @Class All the static error constants
 *
 */
public class ErrorConstants {

	private ErrorConstants() {
	}

	public static final String ERROR_USER_TYPE_EXISTS = "USER_TYPE_EXISTS";
	public static final String ERROR_USER_TYPE_NOT_EXISTS = "USER_TYPE_NOT_EXISTS";

	public static final String ERROR_USER_EXISTS = "USER_EXISTS";
	public static final String ERROR_USER_NOT_EXISTS = "USER_NOT_EXISTS";

	public static final String ERROR_BANK_EXAM_EXISTS = "BANK_EXAM_EXISTS";
	public static final String ERROR_BANK_EXAM_NOT_EXISTS = "BANK_EXAM_NOT_EXISTS";

	public static final String ERROR_STUDENT_USER_EXISTS = "STUDENT_USER_EXISTS";
	public static final String ERROR_STUDENT_USER_NOT_EXISTS = "STUDENT_USER_NOT_EXISTS";

	public static final String ERROR_STUDENT_QUALIFICATION_EXISTS = "STUDENT_QUALIFICATION_EXISTS";
	public static final String ERROR_STUDENT_QUALIFICATION_NOT_EXISTS = "STUDENT_QUALIFICATION_NOT_EXISTS";

	public static final String ERROR_QUESTION_SUB_CATEGORY_EXISTS = "QUESTION_SUB_CATEGORY_EXISTS";
	public static final String ERROR_QUESTION_SUB_CATEGORY_NOT_EXISTS = "QUESTION_SUB_CATEGORY_NOT_EXISTS";
	
	public static final String ERROR_QUESTION_CATEGORY_EXISTS = "QUESTION_CATEGORY_EXISTS";
	public static final String ERROR_QUESTION_CATEGORY_NOT_EXISTS = "QUESTION_CATEGORY_NOT_EXISTS";

	public static final String ERROR_QUESTION_EXISTS = "QUESTION_EXISTS";
	public static final String ERROR_QUESTION_NOT_EXISTS = "QUESTION_NOT_EXISTS";
	public static final String ERROR_INVALID_QUESTION_OPTIONS = "QUESTION_OPTIONS_INVALID";
	
	public static final String ERROR_BANK_QUESTION_CATEGORY_EXISTS = "BANK_QUESTION_CATEGORY_EXISTS";
	public static final String ERROR_BANK_QUESTION_CATEGORY_NOT_EXISTS = "BANK_QUESTION_CATEGORY_NOT_EXISTS";
	
	public static final String ERROR_ASSESSMENT_EXISTS = "ASSESSMENT_EXISTS";
	public static final String ERROR_ASSESSMENT_NOT_EXISTS = "ASSESSMENT_NOT_EXISTS";
	
	public static final String ERROR_EXAM_EXISTS = "EXAM_EXISTS";
	public static final String ERROR_EXAM_NOT_EXISTS = "EXAM_NOT_EXISTS";
	
	public static final String ERROR_QUESTION_TYPE_EXISTS = "QUESTION_TYPE_EXISTS";
	public static final String ERROR_QUESTION_TYPE_NOT_EXISTS = "QUESTION_TYPE_NOT_EXISTS";
	
	public static final String ERROR_QUESTION_FILTER_EXISTS = "QUESTION_FILTER_EXISTS";
	public static final String ERROR_QUESTION_FILTER_NOT_EXISTS = "QUESTION_FILTER_NOT_EXISTS";


	public static final String ERROR_OBJECT_CONVERSION = "OBJECT_CONVERSION_ERROR";
	public static final String ERROR_REJECTION_REASON = "REASON_FOR_REJECTION_NOT_FOUND";
	public static final String ERROR_REASON_LENGTH = "REASON_LENGTH_EXCEPTION";
	public static final String ERROR_GROUP_NAME_EXISTS = "GROUP_NAME_EXISTS";
	public static final String ERROR_APPROVED_GROUP_REJECTION = "APPROVED_GROUP_REJECTION";
	public static final String ERROR_GROUP_ALREADY_APPROVED = "GROUP_ALREADY_APPROVED";
	public static final String ERROR_REJECTED_GROUP_APPROVE = "CANNOT_APPROVE_GROUP_REJECTION";
	public static final String ERROR_ALREADY_REJECTED_GROUP = "GROUP_ALREADY_REJECTED";
	public static final String ERROR_GROUP_INVALID_STATUS = "INVALID_GROUP_STATUS";
	public static final String ERROR_GROUP_ID = "INVALID_GROUPID_EXCEPTION";
	public static final String ERROR_OBJECT_CHANGES = "NO_CHANGES_IN_RECREATION";
	public static final String ERROR_FUNCTION_ID = "INVALID_FUNCTIONID_EXCEPTION";
	public static final String ERROR_GROUP_FUNCION_MAPPING = "GROUP_FUNCION_MAPPING_EXISTS";
	public static final String ERROR_FUNCION_ID = "INVALID_FUNCTIONID_EXCEPTION";
	public static final String ERROR_GROUP_FUNCTION_ID = "INVALID_GROUP_FUNCTIONID_EXCEPTION";
	public static final String ERROR_GROUPUSER_MAPPING_EXISTS = "ERROR_GROUPUSER_MAPPING_EXISTS";
	public static final String ERROR_GROUPUSER_ID_INVALID = "ERROR_GROUPUSER_ID_INVALID";
	public static final String ERROR_USERAGENT_ID_INVALID = "ERROR_USERAGENT_ID_INVALID";
	public static final String ERROR_LEVEL_ID = "ERROR_LEVEL_ID";
	public static final String INVALID_TOKEN = "INVALID_TOKEN";
	public static final String ERROR_KEYCLOAK_CONNECTION_ERROR = "ERROR_KEYCLOAK_CONNECTION_ERROR";
	public static final String ERROR_GROUPUSER_MAPPING_NOTFOUND = "ERROR_GROUPUSER_MAPPING_NOTFOUND";
	public static final String ERROR_UNAUTHORIZED_USER = "ERROR_UNAUTHORIZED_USER";
	public static final String KEY_CLOAK_INVALID_USER = "KEY_CLOAK_INVALID_USER";
	public static final String ERROR_FILE_TYPE = "ERROR_FILE_TYPE";
	public static final String ERROR_FILE_NOT_CREATED = "ERROR_FILE_NOT_CREATED";
	public static final String ERROR_INVALID_MAPPING_STATUS = "INVALID_MAPPING_STATUS";
	public static final String ERROR_IN_AGENT_FETCH = "ERROR_IN_AGENT_FETCH";
	public static final String ERROR_IN_INVALID_AGENT_FETCH_OR_SUPPLIED = "INVALID_AGENT_FETCH_OR_SUPPLIED";
	public static final String ERROR_IN_BRANCH_FETCH = "BRANCH_LIST_FETCH_ERROR";
	public static final String ERROR_INVALID_MAPPING_DETAILS = "INVALID_MAPPING_DETAILS";
	public static final String ERROR_INVALID_USREID_OR_BRANCHID = "INVALID_USREID_OR_BRANCHID";
	public static final String ERROR_AGENT_MAPPING_ALREADY_AVAILABLE = "AGENT_MAPPING_ALREADY_AVAILABLE";
	public static final String ERROR_NO_MAPPINGS_FOUND = "NO_MAPPINGS_FOUND";
	public static final String ERROR_INVALID_BRANCH_ID = "INVALID_BRANCH_ID";
	public static final String ERROR_INVALID_USER_ACCESS_STATUS = "INVALID_USER_ACCESS_STATUS";
	public static final String ERROR_USER_CREATION_ERROR = "USER_CREATION_ERROR";
	public static final String ERROR_USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS";
	public static final String ERROR_EMAILID_ALREADY_EXISTS = "EMAILID_ALREADY_EXISTS";
	public static final String ERROR_USER_INFO_ALREADY_EXISTS = "USER_INFO_ALREADY_EXISTS";
//	public static final String ERROR_USER_NOT_EXISTS = "USER_NOT_EXISTS";
	public static final String ERROR_FUNCTION_NAME_EXISTS = "FUNCTION_NAME_EXISTS";
	public static final String NO_ACTIVE_GROUP_FUNCTIONS_AVAILABLE_TO_EXPORT = "NO_ACTIVE_GROUP_FUNCTIONS_AVAILABLE_TO_EXPORT";
	public static final String NO_ACTIVE_GROUP_USERS_AVAILABLE_TO_EXPORT = "NO_ACTIVE_GROUP_USERS_AVAILABLE_TO_EXPORT";
	public static final String ERROR_PARENT_MENUID_NOT_EXISTS = "INVALID_PARENT_MENUID_SUPPLIED";
	public static final String ERROR_MENU_INVALID_STATUS = "INVALID_MENU_STATUS";
	public static final String ERROR_INVALID_SEARCH_KEY = "INVALID_SEARCH_KEY";
	public static final String ERROR_MAPPING_INVALID_STATUS = "INVALID_MAPPING_STATUS";
	public static final String ERROR_GROUPFUNCTION_ALREADY_AWAITING = "ERROR_GROUPFUNCTION_ALREADY_AWAITING";
	public static final String ERROR_GROUPUSER_ALREADY_AWAITING = "ERROR_GROUPUSER_ALREADY_AWAITING";
	public static final String ERROR_USERGROUP_ALREADY_AWAITING = "ERROR_USERGROUP_ALREADY_AWAITING";
	public static final String ERROR_USERAGENT_ALREADY_AWAITING = "ERROR_USERAGENT_ALREADY_AWAITING";
	public static final String ERROR_IN_GROUP_STATUS_CHANGE_UNTIL_GROUP_AUTHORIZE = "ERROR_IN_GROUP_STATUS_CHANGE_UNTIL_GROUP_AUTHORIZE";
	public static final String ERROR_IN_GROUP_DATA_CHANGE_AFTER_GROUP_AUTHORIZED = "ERROR_IN_GROUP_DATA_CHANGE_AFTER_GROUP_AUTHORIZED";
	public static final String ERROR_IN_GROUPFUNCTION_MAPPING_UNMAPPED_TO_DISABLED = "ERROR_IN_GROUPFUNCTION_MAPPING_UNMAPPED_TO_DISABLED";
	public static final String ERROR_IN_GROUPUSER_MAPPING_UNMAPPED_TO_DISABLED = "ERROR_IN_GROUPUSER_MAPPING_UNMAPPED_TO_DISABLED";
	public static final String ERROR_IN_USERGROUP_MAPPING_UNMAPPED_TO_DISABLED = "ERROR_IN_USERGROUP_MAPPING_UNMAPPED_TO_DISABLED";
	public static final String ERROR_IN_USERAGENT_MAPPING_UNMAPPED_TO_DISABLED = "ERROR_IN_USERAGENT_MAPPING_UNMAPPED_TO_DISABLED";
	public static final String ERROR_GROUP_AUTHORIZATION_NOTAVAILABLE = "ERROR_GROUP_AUTHORIZATION_NOTAVAILABLE";
	public static final String ERROR_USER_AUTHORIZATION_NOTAVAILABLE = "ERROR_USER_AUTHORIZATION_NOTAVAILABLE";
	public static final String ERROR_REQUESTED_STATUS_ALREADY_EXISTS = "ERROR_REQUESTED_STATUS_ALREADY_EXISTS";
	public static final String ERROR_INVALID_MENU_NAME = "INVALID_MENU_NAME";
	public static final String ERROR_RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";
	public static final String ERROR_KEY_CLOAK_SERVER_CONNECTION = "KEY_CLOAK_SERVER_CONNECTION_ERROR";
	public static final String ERROR_KEY_CLOAK_ROLE_CREATION = "UNABLE_CREATED_ROLE";
	public static final String ERROR_KEY_CLOAK_USER_ROLE_MAPPING = "UNABLE_MAP_ROLE_WITH_USER";
	public static final String ERROR_KEY_CLOAK_COMPOSITE_ROLE_MAPPING = "UNABLE_CREATE_COMPOSITE_ROLE";
	public static final String ERROR_ROLE_ALREADY_EXISTS = "ROLE_ALREADY_EXISTS";
	public static final String ERROR_INVALID_CLIENTID_OR_KEYCLOAKCLIENTID = "ERROR_INVALID_CLIENTID_OR_KEYCLOAKCLIENTID";
	public static final String ERROR_ROLE_NAME_ALREADY_EXISTS = "ROLE_NAME_ALREADY_EXISTS";
	public static final String ERROR_COMPOSITE_ROLE_NOT_EXISTS = "COMPOSITE_ROLE_NOT_EXISTS";
	public static final String ERROR_COMPOSITE_ROLE_INVALID = "COMPOSITE_ROLE_INVALID";
	public static final String ERROR_COMPOSITE_ROLE_IN_AWAITING_OR_NOT_ENABLED = "COMPOSITE_ROLE_IN_AWAITING_OR_NOT_ENABLED";
	public static final String ERROR_ROLE_NOT_EXISTS = "ROLE_NOT_EXISTS";
	public static final String ERROR_ROLE_ALREADY_AWAITING = "ERROR_ROLE_ALREADY_AWAITING";
	public static final String ERROR_ROLE_NOT_ENABLED = "ERROR_ROLE_NOT_ENABLED";
	public static final String ERROR_IN_SUPPLIED_CLIENT_INFO_FOR_REALM_ROLE = "ERROR_IN_SUPPLIED_CLIENT_INFO_FOR_REALM_ROLE";
	public static final String ERROR_IN_CLIENT_ROLE_CREATION = "CLIENT_INFORMATION_MISSING";
	public static final String ERROR_USER_ALREADY_AWAITING = "ERROR_USER_ALREADY_AWAITING";
	public static final String ERROR_ON_ROLE_AUTHORIZATION = "ERROR_ON_ROLE_AUTHORIZATION";
	public static final String ERROR_ROLE_NOT_IN_AWAITING = "ERROR_ROLE_NOT_IN_AWAITING";
	public static final String ERROR_USER_ATRRIBUTES_KEYVALUE_NOT_EMPTY = "USER_ATRRIBUTES_KEYVALUE_NOT_EMPTY";
	public static final String ERROR_ROLE_UPDATE_STATUS = "ERROR_ROLE_UPDATE_STATUS";
	public static final String ERROR_INVALID_GROUPNAME_EXCEPTION = "INVALID_GROUPNAME_EXCEPTION";
	public static final String ERROR_USERROLE_MAPPING_EXISTS = "ERROR_USERROLE_MAPPING_EXISTS";
	public static final String ERROR_USERROLE_MAPPING_NOTFOUND = "ERROR_USERROLE_MAPPING_NOTFOUND";
	public static final String ERROR_IN_USERROLE_MAPPING_UNMAPPED_TO_DISABLED = "ERROR_IN_USERROLE_MAPPING_UNMAPPED_TO_DISABLED";
	public static final String ERROR_USERROLE_ALREADY_AWAITING = "ERROR_USERROLE_ALREADY_AWAITING";
	public static final String ERROR_USERROLE_ID_INVALID = "ERROR_USERROLE_ID_INVALID";

}
